[server]
addr = "127.0.0.1:20160"
[storage]
reserve-space = "1MB"
enable-ttl = true
api-version = 2
[pd]
endpoints = ["127.0.0.1:2379"]
[rocksdb]
max-open-files = 10000
[raftdb]
max-open-files = 10000
